name: terraform-apply

on:
  push:
    branches: ["main"]
    paths:
      - "modules/**"
      - "live/**"
      - ".github/workflows/terraform-apply.yml"

permissions:
  id-token: write
  contents: read

jobs:
  apply-dev:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: live
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: terraform init -input=false
      - run: terraform workspace select "${{ vars.TF_WORKSPACE }}" || terraform workspace new "${{ vars.TF_WORKSPACE }}"
      - run: terraform apply -input=false -auto-approve -var-file="${{ vars.TFVARS_FILE }}"

  apply-staging:
    runs-on: ubuntu-latest
    needs: apply-dev
    environment: staging
    defaults:
      run:
        working-directory: live
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: terraform init -input=false
      - run: terraform workspace select "${{ vars.TF_WORKSPACE }}" || terraform workspace new "${{ vars.TF_WORKSPACE }}"
      - run: terraform apply -input=false -auto-approve -var-file="${{ vars.TFVARS_FILE }}"

  apply-prod:
    runs-on: ubuntu-latest
    needs: apply-staging
    environment: prod
    defaults:
      run:
        working-directory: live
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: terraform init -input=false
      - run: terraform workspace select "${{ vars.TF_WORKSPACE }}" || terraform workspace new "${{ vars.TF_WORKSPACE }}"
      - run: terraform apply -input=false -auto-approve -var-file="${{ vars.TFVARS_FILE }}"
